db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://${DB_HOST:stg-db}:${DB_PORT:5432}/${DB_NAME:gymcrm}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=validate
hibernate.show_sql=false
hibernate.format_sql=false

logging.level.com.gym.crm=INFO