spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:gymcrm}
spring.datasource.username=${DB_USERNAME:gymcrm}
spring.datasource.password=${DB_PASSWORD:gymcrm}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.gym.crm=DEBUG
management.endpoint.health.show-details=always